version: '3'
services:
  db:
    image: postgres:9.5
    env_file: '.env'
    volumes:
      - ./sql:/sql
    container_name: eter_db

  mqttpg:
    env_file: '.env'
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    container_name: eter_mqttpg

  metabase:
    image: metabase/metabase
    env_file: '.env'
    container_name: metabase
    ports:
      - "2448:3000"
    depends_on:
      - db

